version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3301:5004"
    restart: always
  frontend:
    build: ./frontend
    ports:
      - "8000:5003"
    restart: always
    depends_on:
      - backend
