version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: "./backend/Dockerfile"
    ports:
      - "3304:5004"
    restart: always
  frontend:
    build:
    context: . 
    dockerfile: "./frontend/Dockerfile"
    ports:
      - "3303:5003"
    restart: always
    depends_on:
      - backend
